version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: scrapesavee-postgres
    environment:
      POSTGRES_DB: scrapesavee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RabbitMQ Message Queue
  rabbitmq:
    image: rabbitmq:3-management
    container_name: scrapesavee-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Worker API
  worker-api:
    build:
      context: ./apps/worker
      dockerfile: Dockerfile
    container_name: scrapesavee-worker-api
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/scrapesavee
      - AMQP_URL=amqp://admin:admin123@rabbitmq:5672/
      - R2_ENDPOINT_URL=https://your-account-id.r2.cloudflarestorage.com
      - R2_ACCESS_KEY_ID=your-access-key
      - R2_SECRET_ACCESS_KEY=your-secret-key
      - R2_BUCKET_NAME=savee
      - ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./apps/worker:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Admin UI
  admin-ui:
    build:
      context: ./apps/admin-ui
      dockerfile: Dockerfile
    container_name: scrapesavee-admin-ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WORKER_API_URL=http://localhost:8001
      - NODE_ENV=production
    depends_on:
      worker-api:
        condition: service_healthy
    volumes:
      - ./apps/admin-ui:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  default:
    name: scrapesavee-network

