name: Scheduled Worker Run

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch:
    inputs:
      max_items:
        description: "Max items per source"
        required: false
        default: "50"
      limit_sources:
        description: "Limit to first N sources"
        required: false
        default: ""

jobs:
  run-worker-once:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libdrm2 \
              libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 \
              libasound2 libatspi2.0-0 libxshmfence1 libx11-xcb1

      - name: Install Python dependencies
        working-directory: apps/worker
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run one scrape cycle
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          AMQP_URL: ${{ secrets.AMQP_URL || '' }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          COOKIES_JSON: ${{ secrets.COOKIES_JSON || '' }}
          COOKIES_PATH: ""
        working-directory: apps/worker
        run: |
          python -m app.cli --max-items "${{ github.event.inputs.max_items || '50' }}" $(
            if [ -n "${{ github.event.inputs.limit_sources }}" ]; then echo --limit-sources "${{ github.event.inputs.limit_sources }}"; fi
          )
